/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: [
    '@vedica/ai-engine',
    '@vedica/analysis-engine',
    '@vedica/ashtakavarga-engine',
    '@vedica/astrology-core',
    '@vedica/bazi-engine',
    '@vedica/benchmark-store',
    '@vedica/chart-renderer',
    '@vedica/compatibility-engine',
    '@vedica/dasha-engine',
    '@vedica/divisional-chart-engine',
    '@vedica/interpretation-engine',
    '@vedica/jaimini-engine',
    '@vedica/life-domain-engine',
    '@vedica/location-engine',
    '@vedica/numerology-engine',
    '@vedica/panchanga-engine',
    '@vedica/query-engine',
    '@vedica/report-engine',
    '@vedica/report-export',
    '@vedica/rules-engine',
    '@vedica/shared',
    '@vedica/shadbala-engine',
    '@vedica/strength-engine',
    '@vedica/timing-engine',
    '@vedica/timeline-engine',
    '@vedica/transit-engine',
    '@vedica/validation',
    '@vedica/yoga-engine',
    '@vedica/ziwei-engine',
    '@vedica/palmistry-engine',
  ],
  serverExternalPackages: ['sweph', 'better-sqlite3', '@libsql/client'],
};

export default nextConfig;
