import { QueryEvidenceItem } from '../types.js';

export interface WhyChain {
  evidenceId: string;
  title: string;
  sourceEngine: string;
  sourceRuleId?: string;
  steps: string[];
}

export function buildWhyChain(item: QueryEvidenceItem): WhyChain {
  const steps: string[] = [
    `1. Engine Execution: Output generated by @vedica/${item.sourceEngine.toLowerCase().replace(/_/g, '-')}`,
    `2. Rule Evaluation: ${item.sourceRuleId || 'STANDARD-RULE'} evaluated for category ${item.category}`,
    `3. Directional Classification: Assigned ${item.direction} classification`,
    ...item.whyEvidence.map((e, idx) => `4.${idx + 1}. Detail: ${e}`),
  ];

  return {
    evidenceId: item.id,
    title: item.title,
    sourceEngine: item.sourceEngine,
    sourceRuleId: item.sourceRuleId,
    steps,
  };
}
